# Generated by Django 6.0.6 on 2026-06-25 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending verification'), ('RETURNED_TO_VERIFIER', 'Returned to verifier'), ('RETURNED_TO_REPORTER', 'Returned to reporter'), ('PENDING_APPROVAL', 'Pending approval'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('involves_person', models.BooleanField(default=False)),
                ('involves_product', models.BooleanField(default=False)),
                ('involves_premises', models.BooleanField(default=False)),
                ('involves_property', models.BooleanField(default=False)),
                ('classification_injury', models.BooleanField(default=False)),
                ('classification_breakdown', models.BooleanField(default=False)),
                ('classification_damage', models.BooleanField(default=False)),
                ('classification_accident', models.BooleanField(default=False)),
                ('classification_fault', models.BooleanField(default=False)),
                ('classification_fire', models.BooleanField(default=False)),
                ('classification_assault', models.BooleanField(default=False)),
                ('classification_power_outage', models.BooleanField(default=False)),
                ('classification_theft_vandalism', models.BooleanField(default=False)),
                ('classification_loss', models.BooleanField(default=False)),
                ('classification_water_shortage', models.BooleanField(default=False)),
                ('classification_other', models.BooleanField(default=False)),
                ('classification_other_text', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(blank=True, choices=[('INSIGNIFICANT', 'Insignificant'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('CATASTROPHIC', 'Catastrophic')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('possible_causes', models.TextField(blank=True)),
                ('corrective_actions_taken', models.TextField(blank=True)),
                ('immediate_actions', models.TextField(blank=True)),
                ('effect_on_process', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('late_reason', models.TextField(blank=True)),
                ('return_comment', models.TextField(blank=True)),
                ('pending_approver_comment', models.TextField(blank=True)),
                ('reporter_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('approver_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_incidents', to=settings.AUTH_USER_MODEL)),
                ('scene_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incidents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(max_length=32)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('VERIFICATION_REJECTED', 'Verification rejected'), ('APPROVED', 'Approved'), ('APPROVAL_REJECTED', 'Approval rejected'), ('COMMENT', 'Comment'), ('RETURNED_TO_REPORTER', 'Returned to reporter'), ('REASSIGNED_VERIFIER', 'Verifier reassigned'), ('REASSIGNED_APPROVER', 'Approver reassigned'), ('LATE_FLAGGED', 'Late submission flagged')], max_length=32)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='incidents.incident')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
