# Generated by Django 5.2.15 on 2026-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='other_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_person_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_premises',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_premises_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_product_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_property_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
